### ISSUE TITLE
smarthomeng does not start File "/usr/local/smarthome/bin/smarthome.py", line 1318, in <module>

### ISSUE THREAD

**Issue by credel** [smarthomeNG/docker#6]
hi,

after the 1.7.1 update i´m getting this error: (smarthomeng is not starting)

smarthome@59bcc7748830:/$ python3 /usr/local/smarthome/bin/smarthome.py -f
Traceback (most recent call last):
  File "/usr/local/smarthome/bin/smarthome.py", line 1318, in <module>
    sh = SmartHome(extern_conf_dir=extern_conf_dir)
  File "/usr/local/smarthome/bin/smarthome.py", line 353, in __init__
    self.shtime._initialize_holidays()
  File "/usr/local/smarthome/lib/shtime.py", line 963, in _initialize_holidays
    location = self.config.get('location', None)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by henfri** [comment]
Hello,

you need to create the holiday.yaml in the configuration folder (etc), as stated in the Documentation of sh.py. 
this is not docker-specific.

Greetings,
Hendrik
